# Generated by Django 3.2.5 on 2021-08-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=12)),
                ('course', models.CharField(max_length=12)),
                ('work_experience', models.CharField(max_length=12)),
                ('contract', models.FileField(null=True, upload_to='images/')),
                ('trainer_gender', models.FileField(max_length=12, upload_to='')),
                ('trainer_id', models.PositiveIntegerField()),
                ('profile_picture', models.ImageField(null=True, upload_to='images/')),
                ('biograph', models.TextField(max_length=300, null=True)),
                ('date_hired', models.DateField()),
                ('national_id', models.CharField(max_length=12)),
                ('language', models.CharField(choices=[('Eng', 'english'), ('Kisw', 'kiswahili')], max_length=20, null=True)),
                ('age', models.PositiveBigIntegerField()),
                ('courses', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20, null=True)),
            ],
        ),
    ]
