# Generated by Django 3.2.5 on 2021-09-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='courses',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='national_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_gender',
            field=models.FileField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='work_experience',
            field=models.CharField(max_length=50),
        ),
    ]
