# Generated by Django 3.2.5 on 2021-08-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12, null=True)),
                ('last_name', models.CharField(max_length=12, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('district', models.CharField(max_length=12, null=True)),
                ('gender', models.CharField(choices=[('1', 'Famale'), ('2', 'Male'), ('3', 'Other')], max_length=12)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('student_id', models.PositiveSmallIntegerField(null=True)),
                ('nationality', models.CharField(choices=[('1', 'kenya'), ('1', 'Rwanda'), ('1', 'uganda')], max_length=17, null=True)),
                ('national_id', models.CharField(max_length=12, null=True)),
                ('medical_report', models.FileField(null=True, upload_to='files/')),
                ('language', models.CharField(max_length=15, null=True)),
                ('laptop_serial_number', models.CharField(max_length=15, null=True)),
                ('date_of_enrollment', models.DateField(null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='image/')),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('role_number', models.CharField(max_length=12, null=True)),
            ],
        ),
    ]
